---
#start of yaml

# This is the yaml config file for both the wazuh-ntfy-notifier.py and wazuh-discord-notifier.py.
# The yaml needs to be in the same folder as the wazuh-ntfy-notifier.py and wazuh-discord-notifier.py

# COMMON configuration settings start here.
# 1 =  messages will be sent through this message server. 0 = messages will NOT be sent through this message server.

discord_enabled: 1
ntfy_enabled: 1

# COMMON configuration settings start here.


# NTFY configuration settings start here.
# The default values refer to the hard-coded defaults, if no yaml configuration is found.
#
# -u, --server        is the URL of the NTFY server, ending with a "/". Default is https://ntfy.sh/.
# -s, --sender        is the sender of the message, either an app name or a person. Default is "Wazuh (IDS)".
# -d, --destination   is the NTFY subscription, to send the message to. Default is none.
# -p, --priority      is the priority of the message, ranging from 1 (highest), to 5 (lowest). Default is 5.
# -m, --message       is the text of the message to be sent. Default is "Test message".
# -t, --tags          is an arbitrary strings of tags (keywords), seperated by a "," (comma). Default is "informational, testing, hard-coded".
# -c, --click         is a link (URL) that can be followed by tapping/clicking inside the message. Default is https://google.com.
# -h, --help          shows this help message. Must have no value argument.
# -v, --view          show config.

ntfy_server: "https://ntfy.sh/"
ntfy_sender: "Wazuh (IDS)"
ntfy_destination: "__KleinTest"
ntfy_priority: "5"
ntfy_message: "Test message"
ntfy_tags: "information, testing, yaml"
ntfy_click: "https://google.com"

# NTFY configuration settings ends here.

# DISCORD configuration settings start here.
# The default values refer to the hard-coded defaults, if no yaml configuration is found.

# -u, --server        is the webhook URL of the Discord server. It is stored in .env.
# -s, --sender        is the sender of the message, either an app name or a person. The default is "Security message".
# -d, --destination   is the destination (actually the originator) of the message, either an app name or a person. Default is "Wazuh (IDS)"
# -p, --priority      is the priority of the message, ranging from 1 (highest), to 5 (lowest). Default is 5.
# -m, --message       is the text of the message to be sent. Default is "Test message", but may include --tags and/or --click.
# -t, --tags          is an arbitrary strings of tags (keywords), seperated by a "," (comma). Default is "informational, testing, hard-coded".
# -c, --click         is a link (URL) that can be followed by tapping/clicking inside the message. Default is https://google.com.
# -h, --help          shows this help message. Must have no value argument.
# -v, --view          show config.

discord_server: "not used. The webhook (server) is a secret stored in .env"
discord_sender: "Security message"
discord_destination: "WAZUH (IDS)"
discord_priority: "5"
discord_message: "Test message"
discord_tags: "informational, testing, yaml"
discord_click: "https://google.com"

# DISCORD configuration settings ends here.

#end of yaml
...



