---
#start of yaml

# This is the yaml config file for both the wazuh-ntfy-notifier.py and wazuh-discord-notifier.py.
# The yaml needs to be in the same folder as the wazuh-ntfy-notifier.py and wazuh-discord-notifier.py

# COMMON (custom-wazuh-notifiers.py) configuration settings start here.
# 1 =  messages will be sent through this message server. 0 = messages will NOT be sent through this message server.

targets: "discord,ntfy"

# Exclude rules that are listed in the ossec.conf active response definition.

excluded_rules: "5401, 5403"
excluded_agents: "999"

# Priority mapping from 1-12 (Wazuh events) to 1-5 (Discord and ntfy notification)

priority_1: 12, 11, 10
priority_2: 9, 8
priority_3: 7, 6
priority_4: 5, 4
priority_5: 3 ,2, 1

sender: "Wazuh (IDS)"
click: "https://google.com"


#end of yaml
...



