---
#start of yaml

# This is the yaml config file for both the wazuh-ntfy-notifier.py and wazuh-discord-notifier.py.
# The yaml needs to be in the same folder as the wazuh-ntfy-notifier.py and wazuh-discord-notifier.py

targets: "discord,ntfy"
full_message: "ntfy"

# Exclude rules that are listed in the ossec.conf active response definition.

excluded_rules: "5401,5403"
excluded_agents: "999"

# Priority mapping from 1-12 (Wazuh events) to 1-5 (Discord and ntfy notification)
# Discord mention after x amount of event fired times

priority_map:
  -
    threat_map: [15,14,13,12]
    mention_threshold: 1
  -
    threat_map: [11,10,9]
    mention_threshold: 1
  -
    threat_map: [8,7,6]
    mention_threshold: 5
  -
    threat_map: [5,4]
    mention_threshold: 5
  -
    threat_map: [3,2,1,0]
    mention_threshold: 5


sender: "Wazuh (IDS)"
click: "https://google.com"


#end of yaml
...



