# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        
    - name: tset
      run: ls -all

    - name: Build
      run: go build -v ./wazuh-notify-go
      
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          wazuh-notify-go/wazuh-notify

          
