# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'      

    - name: Build
      run: |
        cd wazuh-notify-go
        go build -v .
        
    - name: Put current date into a variable
      run: |
        $NOW=& Get-Date -format yyyy-MM-dd
        echo "NOW=$NOW" >> $env:GITHUB_ENV
      
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        tag_name: Golang vx.x.x
        files: |
          wazuh-notify-go/wazuh-notify
