# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: |
        cd wazuh-notify-go
        go build -v .

    - name: Set go variables
      run: |
        cd wazuh-notify-go && GO_VER=$(cat VERSION)
        echo "GO_VERSION=$GO_VER" >> $GITHUB_ENV       
      
    - name: Release Go
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        tag_name: Golang-v${{ env.GO_VERSION }}
        files: |
          wazuh-notify-go/wazuh-notify
          wazuh-notify-go/wazuh-notify-config.toml
          licence.MD

    - name: Set python variables
      run: |
        cd wazuh-notify-python && PY_VER=$(cat VERSION)
        echo "PY_VERSION=$PY_VER" >> $GITHUB_ENV

    - name: zip Python
      run: zip -r wazuh-notify-python.zip wazuh-notify-python wazuh-notify-go/wazuh-notify-config.toml

    - name: Release python
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        tag_name: Python-v${{ env.PY_VERSION }}
        files: |
          wazuh-notify-python.zip
          licence.MD
